import { MultiLevelData } from '@/hooks/useMultiLevelFilter/useMultiLevelFilter';

export const festivalRegionFilter: MultiLevelData[] = [
  {
    label: '서울특별시',
    value: 'seoul',
    children: [
      { label: '강남구', value: 'gangnam' },
      { label: '강동구', value: 'gangdong' },
      { label: '강북구', value: 'gangbuk' },
      { label: '강서구', value: 'gangseo' },
      { label: '관악구', value: 'gwanak' },
      { label: '광진구', value: 'gwangjin' },
      { label: '구로구', value: 'guro' },
      { label: '금천구', value: 'geumcheon' },
      { label: '노원구', value: 'nowon' },
      { label: '도봉구', value: 'dobong' },
      { label: '동대문구', value: 'dongdaemun' },
      { label: '동작구', value: 'dongjak' },
      { label: '마포구', value: 'mapo' },
      { label: '서대문구', value: 'seodaemun' },
      { label: '서초구', value: 'seocho' },
      { label: '성동구', value: 'seongdong' },
      { label: '성북구', value: 'seongbuk' },
      { label: '송파구', value: 'songpa' },
      { label: '양천구', value: 'yangcheon' },
      { label: '영등포구', value: 'yeongdeungpo' },
      { label: '용산구', value: 'yongsan' },
      { label: '은평구', value: 'eunpyeong' },
      { label: '종로구', value: 'jongno' },
      { label: '중구', value: 'jung' },
      { label: '중랑구', value: 'jungnang' },
    ],
  },
  {
    label: '부산광역시',
    value: 'busan',
    children: [
      { label: '강서구', value: 'busan-gangseo' },
      { label: '금정구', value: 'geumjeong' },
      { label: '기장군', value: 'gijang' },
      { label: '남구', value: 'busan-nam' },
      { label: '동구', value: 'busan-dong' },
      { label: '동래구', value: 'dongnae' },
      { label: '부산진구', value: 'busanjin' },
      { label: '북구', value: 'busan-buk' },
      { label: '사상구', value: 'sasang' },
      { label: '사하구', value: 'saha' },
      { label: '서구', value: 'busan-seo' },
      { label: '수영구', value: 'suyeong' },
      { label: '연제구', value: 'yeonje' },
      { label: '영도구', value: 'yeongdo' },
      { label: '중구', value: 'busan-jung' },
      { label: '해운대구', value: 'haeundae' },
    ],
  },
  {
    label: '대구광역시',
    value: 'daegu',
    children: [
      { label: '남구', value: 'daegu-nam' },
      { label: '달서구', value: 'dalseo' },
      { label: '달성군', value: 'dalseong' },
      { label: '동구', value: 'daegu-dong' },
      { label: '북구', value: 'daegu-buk' },
      { label: '서구', value: 'daegu-seo' },
      { label: '수성구', value: 'suseong' },
      { label: '중구', value: 'daegu-jung' },
    ],
  },
  {
    label: '인천광역시',
    value: 'incheon',
    children: [
      { label: '강화군', value: 'ganghwa' },
      { label: '계양구', value: 'gyeyang' },
      { label: '남동구', value: 'namdong' },
      { label: '동구', value: 'incheon-dong' },
      { label: '미추홀구', value: 'michuhol' },
      { label: '부평구', value: 'bupyeong' },
      { label: '서구', value: 'incheon-seo' },
      { label: '연수구', value: 'yeonsu' },
      { label: '옹진군', value: 'ongjin' },
      { label: '중구', value: 'incheon-jung' },
    ],
  },
  {
    label: '광주광역시',
    value: 'gwangju',
    children: [
      { label: '광산구', value: 'gwangsan' },
      { label: '남구', value: 'gwangju-nam' },
      { label: '동구', value: 'gwangju-dong' },
      { label: '북구', value: 'gwangju-buk' },
      { label: '서구', value: 'gwangju-seo' },
    ],
  },
  {
    label: '대전광역시',
    value: 'daejeon',
    children: [
      { label: '대덕구', value: 'daedeok' },
      { label: '동구', value: 'daejeon-dong' },
      { label: '서구', value: 'daejeon-seo' },
      { label: '유성구', value: 'yuseong' },
      { label: '중구', value: 'daejeon-jung' },
    ],
  },
  {
    label: '울산광역시',
    value: 'ulsan',
    children: [
      { label: '남구', value: 'ulsan-nam' },
      { label: '동구', value: 'ulsan-dong' },
      { label: '북구', value: 'ulsan-buk' },
      { label: '울주군', value: 'ulju' },
      { label: '중구', value: 'ulsan-jung' },
    ],
  },
  {
    label: '세종특별자치시',
    value: 'sejong',
    children: [{ label: '세종시', value: 'sejong-city' }],
  },
  {
    label: '경기도',
    value: 'gyeonggi',
    children: [
      { label: '가평군', value: 'gapyeong' },
      { label: '고양시', value: 'goyang' },
      { label: '과천시', value: 'gwacheon' },
      { label: '광명시', value: 'gwangmyeong' },
      { label: '광주시', value: 'gyeonggi-gwangju' },
      { label: '구리시', value: 'guri' },
      { label: '군포시', value: 'gunpo' },
      { label: '김포시', value: 'gimpo' },
      { label: '남양주시', value: 'namyangju' },
      { label: '동두천시', value: 'dongducheon' },
      { label: '부천시', value: 'bucheon' },
      { label: '성남시', value: 'seongnam' },
      { label: '수원시', value: 'suwon' },
      { label: '시흥시', value: 'siheung' },
      { label: '안산시', value: 'ansan' },
      { label: '안성시', value: 'anseong' },
      { label: '안양시', value: 'anyang' },
      { label: '양주시', value: 'yangju' },
      { label: '양평군', value: 'yangpyeong' },
      { label: '여주시', value: 'yeoju' },
      { label: '연천군', value: 'yeoncheon' },
      { label: '오산시', value: 'osan' },
      { label: '용인시', value: 'yongin' },
      { label: '의왕시', value: 'uiwang' },
      { label: '의정부시', value: 'uijeongbu' },
      { label: '이천시', value: 'icheon' },
      { label: '파주시', value: 'paju' },
      { label: '평택시', value: 'pyeongtaek' },
      { label: '포천시', value: 'pocheon' },
      { label: '하남시', value: 'hanam' },
      { label: '화성시', value: 'hwaseong' },
    ],
  },
  {
    label: '강원도',
    value: 'gangwon',
    children: [
      { label: '강릉시', value: 'gangneung' },
      { label: '고성군', value: 'gangwon-goseong' },
      { label: '동해시', value: 'donghae' },
      { label: '삼척시', value: 'samcheok' },
      { label: '속초시', value: 'sokcho' },
      { label: '양구군', value: 'yanggu' },
      { label: '양양군', value: 'yangyang' },
      { label: '영월군', value: 'yeongwol' },
      { label: '원주시', value: 'wonju' },
      { label: '인제군', value: 'inje' },
      { label: '정선군', value: 'jeongseon' },
      { label: '철원군', value: 'cheorwon' },
      { label: '춘천시', value: 'chuncheon' },
      { label: '태백시', value: 'taebaek' },
      { label: '평창군', value: 'pyeongchang' },
      { label: '홍천군', value: 'hongcheon' },
      { label: '화천군', value: 'hwacheon' },
      { label: '횡성군', value: 'hoengseong' },
    ],
  },
  {
    label: '충청북도',
    value: 'chungbuk',
    children: [
      { label: '괴산군', value: 'goesan' },
      { label: '단양군', value: 'danyang' },
      { label: '보은군', value: 'boeun' },
      { label: '영동군', value: 'yeongdong' },
      { label: '옥천군', value: 'okcheon' },
      { label: '음성군', value: 'eumseong' },
      { label: '제천시', value: 'jecheon' },
      { label: '진천군', value: 'jincheon' },
      { label: '청주시', value: 'cheongju' },
      { label: '충주시', value: 'chungju' },
      { label: '증평군', value: 'jeungpyeong' },
    ],
  },
  {
    label: '충청남도',
    value: 'chungnam',
    children: [
      { label: '계룡시', value: 'gyeryong' },
      { label: '공주시', value: 'gongju' },
      { label: '금산군', value: 'geumsan' },
      { label: '논산시', value: 'nonsan' },
      { label: '당진시', value: 'dangjin' },
      { label: '보령시', value: 'boryeong' },
      { label: '부여군', value: 'buyeo' },
      { label: '서산시', value: 'seosan' },
      { label: '서천군', value: 'seocheon' },
      { label: '아산시', value: 'asan' },
      { label: '예산군', value: 'yesan' },
      { label: '천안시', value: 'cheonan' },
      { label: '청양군', value: 'cheongyang' },
      { label: '태안군', value: 'taean' },
      { label: '홍성군', value: 'hongseong' },
    ],
  },
  {
    label: '전라북도',
    value: 'jeonbuk',
    children: [
      { label: '고창군', value: 'gochang' },
      { label: '군산시', value: 'gunsan' },
      { label: '김제시', value: 'gimje' },
      { label: '남원시', value: 'namwon' },
      { label: '무주군', value: 'muju' },
      { label: '부안군', value: 'buan' },
      { label: '순창군', value: 'sunchang' },
      { label: '완주군', value: 'wanju' },
      { label: '익산시', value: 'iksan' },
      { label: '임실군', value: 'imsil' },
      { label: '장수군', value: 'jangsu' },
      { label: '전주시', value: 'jeonju' },
      { label: '정읍시', value: 'jeongeup' },
      { label: '진안군', value: 'jinan' },
    ],
  },
  {
    label: '전라남도',
    value: 'jeonnam',
    children: [
      { label: '강진군', value: 'gangjin' },
      { label: '고흥군', value: 'goheung' },
      { label: '곡성군', value: 'gokseong' },
      { label: '광양시', value: 'gwangyang' },
      { label: '구례군', value: 'gurye' },
      { label: '나주시', value: 'naju' },
      { label: '담양군', value: 'damyang' },
      { label: '목포시', value: 'mokpo' },
      { label: '무안군', value: 'muan' },
      { label: '보성군', value: 'boseong' },
      { label: '순천시', value: 'suncheon' },
      { label: '신안군', value: 'sinan' },
      { label: '여수시', value: 'yeosu' },
      { label: '영광군', value: 'yeonggwang' },
      { label: '영암군', value: 'yeongam' },
      { label: '완도군', value: 'wando' },
      { label: '장성군', value: 'jangseong' },
      { label: '장흥군', value: 'jangheung' },
      { label: '진도군', value: 'jindo' },
      { label: '함평군', value: 'hampyeong' },
      { label: '해남군', value: 'haenam' },
      { label: '화순군', value: 'hwasun' },
    ],
  },
  {
    label: '경상북도',
    value: 'gyeongbuk',
    children: [
      { label: '경산시', value: 'gyeongsan' },
      { label: '경주시', value: 'gyeongju' },
      { label: '고령군', value: 'goryeong' },
      { label: '구미시', value: 'gumi' },
      { label: '군위군', value: 'gunwi' },
      { label: '김천시', value: 'gimcheon' },
      { label: '문경시', value: 'mungyeong' },
      { label: '봉화군', value: 'bonghwa' },
      { label: '상주시', value: 'sangju' },
      { label: '성주군', value: 'seongju' },
      { label: '안동시', value: 'andong' },
      { label: '영덕군', value: 'yeongdeok' },
      { label: '영양군', value: 'yeongyang' },
      { label: '영주시', value: 'yeongju' },
      { label: '영천시', value: 'yeongcheon' },
      { label: '예천군', value: 'yecheon' },
      { label: '울릉군', value: 'ulleung' },
      { label: '울진군', value: 'uljin' },
      { label: '의성군', value: 'uiseong' },
      { label: '청도군', value: 'cheongdo' },
      { label: '청송군', value: 'cheongsong' },
      { label: '칠곡군', value: 'chilgok' },
      { label: '포항시', value: 'pohang' },
    ],
  },
  {
    label: '경상남도',
    value: 'gyeongnam',
    children: [
      { label: '거제시', value: 'geoje' },
      { label: '거창군', value: 'geochang' },
      { label: '고성군', value: 'gyeongnam-goseong' },
      { label: '김해시', value: 'gimhae' },
      { label: '남해군', value: 'namhae' },
      { label: '밀양시', value: 'miryang' },
      { label: '사천시', value: 'sacheon' },
      { label: '산청군', value: 'sancheong' },
      { label: '양산시', value: 'yangsan' },
      { label: '의령군', value: 'uiryeong' },
      { label: '진주시', value: 'jinju' },
      { label: '창녕군', value: 'changnyeong' },
      { label: '창원시', value: 'changwon' },
      { label: '통영시', value: 'tongyeong' },
      { label: '하동군', value: 'hadong' },
      { label: '함안군', value: 'haman' },
      { label: '함양군', value: 'hamyang' },
      { label: '합천군', value: 'hapcheon' },
    ],
  },
  {
    label: '제주특별자치도',
    value: 'jeju',
    children: [
      { label: '서귀포시', value: 'seogwipo' },
      { label: '제주시', value: 'jeju-city' },
    ],
  },
];
