name: Pull Request Template
description: GitHub PR 템플릿
title: "[PR 유형] "
body:
  - type: dropdown
    id: pr-type
    attributes:
      label: PR 유형
      description: 이 PR의 유형을 선택해주세요
      options:
        - 신규 기능 추가
        - 버그 수정
        - 리펙토링
        - 문서 업데이트
        - 기타
    validations:
      required: true
      
  - type: textarea
    id: changes-reason
    attributes:
      label: 변경사항 및 이유
      description: 변경사항과 그 이유를 bullet 포인트로 작성해주세요
      placeholder: "- 이유"
    validations:
      required: true
      
  - type: textarea
    id: work-details
    attributes:
      label: 작업 내역
      description: 작업 내역을 bullet 포인트로 작성해주세요
      placeholder: "- 작업 내역"
    validations:
      required: true
      
  - type: textarea
    id: expected-behavior
    attributes:
      label: 작업 후 기대 동작
      description: 작업 후 기대되는 동작을 설명해주세요 (스크린샷 첨부 가능)
      placeholder: "- 동작"
    validations:
      required: false
      
  - type: textarea
    id: special-notes
    attributes:
      label: PR 특이 사항
      description: PR과 관련된 특이 사항이 있다면 작성해주세요
      placeholder: "- 특이 사항"
    validations:
      required: false
      
  - type: input
    id: issue-number
    attributes:
      label: Issue Number
      description: 관련된 이슈 번호를 입력해주세요
      placeholder: "close: #이슈번호"
    validations:
      required: false